### ISSUE TITLE
Zero Division

### ISSUE THREAD

**Issue by erikbgithub** [mazzalab/fastqwiper#1]
Hi, found a little division by zero error.

If you get into [this if case](https://github.com/mazzalab/fastqwiper/blob/d9642afe2b5ac12b16dc1c52904ce640b4d52dbe/fastq_wiper/wiper.py#L71) then `tot_lines` will be zero [here](https://github.com/mazzalab/fastqwiper/blob/d9642afe2b5ac12b16dc1c52904ce640b4d52dbe/fastq_wiper/wiper.py#L182).

**Comment by mazzalab** [comment]
We have fixed it. Thanks
