### ISSUE TITLE
zlib.error: Error -3 while decompressing data: invalid block type

### ISSUE THREAD

**Issue by sjfleck** [mazzalab/fastqwiper#12]
Hello,
I have what I believe to be a corrupted fastq.gz file for Oxford Nanopore reads. I tested a few things that failed. When I run gunzip, I get this error:
gzip: FILE.fastq.gz: invalid compressed data--format violated

Original fastq.gz file: 39.9 GB
Gunzipped file (for what able to be decompressed): 60.4 GB

To the best of my understanding, each entry in a fastq file has 4 lines:
1. @SEQ_ID
2. sequence
3. +
4. quality scores

The final 15 lines from the fastq file are where this pattern starts to fail. If I remove the final 15 lines from the decompressed fastq file, I think I can use this subsample for genome assembly etc. 

That said, I wanted to salvage as much as possible, so I found this program. Unfortunately, it fails with the same error as NanoPlot:
zlib.error: Error -3 while decompressing data: invalid block type

The resulting fastqwiper fastq.gz. output was 29.4 GB out of the original 39.9 GB file

I'm not completely familiar with how gzip compression works. If theres corruption at some spot in the middle, is everything after that spot no longer salvageable? Is that final 10 GB lost forever?

Thank you for any help you can provide,
Steve

**Comment by mazzalab** [comment]
Hi Steve,
Can you tell us how you installed fastqwiper and what's the command line you have used?

**Comment by sjfleck** [comment]
I installed fastqwiper using a conda environment from the instructions on your github page and this is the command I used:

fastqwiper --fastq_in $SAMPLE.fastq.gz --fastq_out $SAMPLE.wiped.fastq.gz --log_out $SAMPLE.wiped.log --log_frequency 10,000

**Comment by mazzalab** [comment]
Since your problem seems to be related to the gzip decompression, I suggest using the FastqWiper Docker pipelines. Please follow the procedure here: https://github.com/mazzalab/fastqwiper#cases-2--3

**Comment by sjfleck** [comment]
Is there an alternative option? I'm not very familiar with docker and I work on a university cluster where I don't have root access.

**Comment by mazzalab** [comment]
yes, send us the file and we will do it for you ;)

**Comment by sjfleck** [comment]
How do you recommend I send the file?

**Comment by mazzalab** [comment]
You can use, for example, MEGA, or Dropbox, or Google drive. Just send a link to download the file. If this is a mate of a paired-end couple of files (R1 and R2), it is better to send us both files (R1 and R2).

**Comment by sjfleck** [comment]
Here is the link to the file on Google Drive:
https://drive.google.com/file/d/11hz49bKqc2NWhVwbLPCAH18RNZjeOroV/view?usp=drive_link

Let me know if you have issues gaining access. Thank you

EDIT: I had 2 sets of ONT reads. I discovered only the one set (~30 GB) have some sort of corruption that cause the error, so that's what I shared.

**Comment by mazzalab** [comment]
OK. Please accept my request to share with my email address

**Comment by sjfleck** [comment]
I just made you an editor. Let me know if there are any issues. Thank you

**Comment by mazzalab** [comment]
download from here: https://mega.nz/file/SgETCTJQ#e0O_0YUeGEEOqrMVYpfL_2rKj8GBpxwY2KqvKRIl78U

**Comment by sjfleck** [comment]
Thank you for running fastqwiper and getting my file back to me so quickly. I appreciate it. I'm uploading it to my cluster now and will run NanoPlot as soon as the upload finishes. Can you please tell me any relevant command options and the version number that was used to fix the file? Thank you

EDIT: also, is there a publication for citing fastqwiper?

**Comment by mazzalab** [comment]
Hi Steve, the version is 1.0.5-alpha and the command line was 
`docker run --rm -ti --name fastqwiper -v "YOUR_LOCAL_PATH_TO_DATA_FOLDER:/fastqwiper/data" mazzalab/fastqwiper single 8 SAMPLE_pass 5000000`
where `YOUR_LOCAL_PATH_TO_DATA_FOLDER` was the full path to the folder where I put your file.

No, we haven't published the tool yet. Maybe in the future, after collecting a few more user feedbacks and ... will get some more github stars ;)

hope it was useful
