### ISSUE TITLE
Incremented fastq size after fastqwiper

### ISSUE THREAD

**Issue by mlarjim** [mazzalab/fastqwiper#14]
Hi!
I'm using fastqwiper workflow to heal some corrupted paired end sequencing FASTQs. I expect the `*_fixed_wiped_paired_interleaving.fastq.gz` to have a smaller file size than the corrupted original one because the uncomplete reads entries should be removed, but size has increased. Even the R2 fastq, which was not corrupt, has a larger size. 

Why does the file size increase?

**Comment by mazzalab** [comment]
Hi,
FastqWiper workflows invoke a few third-party softwares that work well with fastq.gz files. It is not excluded that they keep the compression level to the minimum to advantage speed when producing fastq.gz files as their result. 
Unfortunately, this is not under our control.

**Comment by mlarjim** [comment]
ok, thank you!
