### ISSUE TITLE
Missing input files for rule fix_gzrt error

### ISSUE THREAD

**Issue by osmanmerdan** [mazzalab/fastqwiper#15]
Hi, 
I have an issue with fastqwiper docker version on a Linux server.  I have a folder named `single_end` with two fastq files. (`example1.fastq.gz`  `example2.fastq.gz`)  I run the following command and get the error below: 

`/pool/home/my_user_name` : is my user directory in the server. Where the `single_end` folder located. 

Command: 

`docker run --rm -ti --name fastqwiper -v "single_end:/fastqwiper/data" mazzalab/fastqwiper single 8 sample 50000000`

Error: 
Processing single-end file in parallel
Building DAG of jobs...
MissingInputException in rule fix_gzrt in file /fastqwiper/pipeline/fix_wipe_single_reads_parallel.smk, line 13:
Missing input files for rule fix_gzrt:
    output: data/sample_fixed.fastq
    wildcards: sample=sample
    affected files:
        data/sample.fastq.gz

What could be the possible course for this error? I suspected it may be related to file permissions, but the fastq files have read and write permissions for every user. Issue is not probably related to the program directly. But I don't have any issues running other dockerized programs. Maybe you can suggest a fix. Thanks in advance.

**Comment by mazzalab** [comment]
Dear Merdan
Your command line should be

docker run --rm -ti --name fastqwiper -v "single_end:/fastqwiper/data" mazzalab/fastqwiper single 8 example1 50000000

and then

docker run --rm -ti --name fastqwiper -v "single_end:/fastqwiper/data" mazzalab/fastqwiper single 8 example2 50000000

Remember that 
"For single end/individual files (e.g., "excerpt_R1_001.fastq.gz"), your file must end with the string .fastq.gz; the preceding text, i.e., "excerpt_R1_001" in this case, will be the text to be passed to the command as an argument."

Moreover, I'm not sure if this "single_end:/fastqwiper/data" will work or you need to specify the full static path to your 'single_end' folder

**Comment by osmanmerdan** [comment]
Thank you for your quick response. Yes, you were right! I needed to provide an absolute path. It worked!
