### ISSUE TITLE
PKG_VERSION

### ISSUE THREAD

**Issue by erikbgithub** [mazzalab/fastqwiper#2]
I‘m not sure where [the `PKG_VERSION` comes from](https://github.com/mazzalab/fastqwiper/blob/d9642afe2b5ac12b16dc1c52904ce640b4d52dbe/setup.py#L28). I tried to install via clone and `pip install -e`.

Also, could you share why Python 3.9 is excluded?

**Comment by mazzalab** [comment]
We resort now to guthub actions and, therefore, have dropped the previous CI workflow.
We now support Python >3.6 and <3.11 (one of our dependencies does not support 3.11 yet). We will replace it in the future
