### ISSUE TITLE
/usr/bin/bash: /cluster/home/fanrong/.local/bin/fastqwiper: /opt/simplehpc/miniconda3/bin/python: 解释器错误: No such file or directory

### ISSUE THREAD

**Issue by fan040** [mazzalab/fastqwiper#20]
Hello, I have run this snakemake many times and sometimes encountered such errors, but my python exists, I would like to ask how I should modify snakemake so that such errors can not occur.

This is slurm error:
Assuming unrestricted shared filesystem usage.
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.
Job stats:
job                 count
----------------  -------
all                     1
drop_unpaired           1
fix_gzrt                2
fix_interleaving        1
wipe_fastq              2
total                   7

Select jobs to execute...
Execute 2 jobs...

[Tue May 28 08:41:33 2024]
Job 6: Dropping unreadable reads from data/D900905_R2.fastq.gz.
Reason: Missing output files: data/D900905_R2_fixed.fastq

[Tue May 28 08:41:34 2024]
Job 4: Dropping unreadable reads from data/D900905_R1.fastq.gz.
Reason: Missing output files: data/D900905_R1_fixed.fastq

[Tue May 28 08:43:41 2024]
Finished job 4.
1 of 7 steps (14%) done
Select jobs to execute...
Execute 1 jobs...

[Tue May 28 08:43:41 2024]
Job 3: Running FastqWiper on data/D900905_R1_fixed.fastq.
Reason: Missing output files: data/D900905_R1_fixed_wiped.fastq.gz; Input files updated by another job: data/D900905_R1_fixed.fastq

[Tue May 28 08:43:41 2024]
Error in rule wipe_fastq:
    jobid: 3
    input: data/D900905_R1_fixed.fastq
    output: data/D900905_R1_fixed_wiped.fastq.gz
    log: logs/wipe_fastq/wipe_fastq.D900905_R1.log (check log file(s) for error details)
    shell:
    fastqwiper --fastq_in data/D900905_R1_fixed.fastq --fastq_out data/D900905_R1_fixed_wiped.fastq.gz --log_out data/D900905_R1_final_summary.txt 2> logs/wipe_fastq/wipe_fastq.D900905_R1.log
    
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

[Tue May 28 08:43:49 2024]
Finished job 6.
2 of 7 steps (29%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-05-28T084132.828319.snakemake.log
WorkflowError:
At least one job did not complete successfully.

This is log file:
/usr/bin/bash: /cluster/home/fanrong/.local/bin/fastqwiper: /opt/simplehpc/miniconda3/bin/python: 解释器错误: No such file or directory

**Comment by mazzalab** [comment]
Hi,
Can you report the way you installed FastqWiper?

Thanks

**Comment by fan040** [comment]
I use fastqwiper conda installed under the environment of software, and also to clone the git clone https://github.com/mazzalab/fastqwiper.git, is the reason?

**Comment by mazzalab** [comment]
Try to install fastqwiper in a fresh new environment. Strictly follow the instructions and let us know if you still have problems.
In that case, please report all command lines you used to install and run the software.

**Comment by mazzalab** [comment]
Close for inactivity
