### ISSUE TITLE
Empty output expected?

### ISSUE THREAD

**Issue by bcantarel** [mazzalab/fastqwiper#3]
I tried running on a small file with some formatting issues, ie duplicate sequences, not having the proper number of lines per record, etc.  The resulting file is empty.  Is that expected?

> fastqwiper --fastq_in smallONT.fastq --fastq_out smallONT.fix.fastq 
Start wiping smallONT.fastq
Successfully terminated

Wiped lines: 0/19580 (0.0%)
Len(SEQ) neq Len(QUAL): 0/19580
BAD QUAL lines: 0/19580
BAD + lines: 0/19580
BAD SEQ lines: 206/19580
Not printable header lines: 0/19580
Not printable qual lines: 0/19580
Fixed header lines: 4702/19580
Fixed + lines: 90/19580
Blank lines: 0/19580
Missplaced lines: 0/19580

> ls -lh smallONT.fix.fastq
-rw-r--r-- 1 root root 0 Feb  5 15:15 smallONT.fix.fastq

**Comment by mazzalab** [comment]
Hi, can you share a test file with us? (bioinformatics@css-mendel.it)

**Comment by mazzalab** [comment]
Due to inactivity, I'm closing this issue
