### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by avinashkarkada** [mazzalab/fastqwiper#7]
conda installation causes the following error:

The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.35=0
  - feature:|@/linux-64::__glibc==2.35=0

**Comment by mazzalab** [comment]
We need more information to help you with this error.

1. OS
2. conda version
3. all commands executed
4. the complete text of the error

**Comment by avinashkarkada** [comment]
These are the details:

OS: Ubuntu 22.04.3 LTS

Conda: 23.5.2

Commands:
`conda create -n fastqwiper python=3.10`
`conda activate fastqwiper` 
`conda install -c bfxcss fastqwiper`

Error: [error.log](https://github.com/mazzalab/fastqwiper/files/12743630/error.log)

**Comment by mazzalab** [comment]
Thanks. We will try to reproduce the error amd will get back to you soon.

**Comment by mazzalab** [comment]
> These are the details:
> 
> OS: Ubuntu 22.04.3 LTS
> 
> Conda: 23.5.2
> 
> Commands: `conda create -n fastqwiper python=3.10` `conda activate fastqwiper` `conda install -c bfxcss fastqwiper`
> 
> Error: [error.log](https://github.com/mazzalab/fastqwiper/files/12743630/error.log)

In the meantime, can you try the command:

`conda install -c bfxcss -c conda-forge fastqwiper`

In place of

`conda install -c bfxcss fastqwiper`

**Comment by avinashkarkada** [comment]
Thank you for your suggestion. I tried using the `conda install -c bfxcss -c conda-forge fastqwiper` command. It worked!!
