### ISSUE TITLE
Error with Docker file

### ISSUE THREAD

**Issue by kimal999** [mazzalab/fastqwiper#8]
Hi,

I have below error with the Docker image.  I'm running it via "singularity" with below command.

`singularity run fastqwiper.sif paired 4 sample 50000000 -v 'YOUR_LOCAL_PATH_TO_DATA_FOLDER:/fastqwiper/data'`

Error message

`Processing paired-end files`
`Error: Snakefile "pipeline/fix_wipe_pairs_reads.smk" not found.`
Is this a problem due to my command?

**Comment by mazzalab** [comment]
Hi,
we currently do not distribute FastqWiper as a Singularity container and haven't tested the Docker-to-Singularity conversion process. It is - however - one of our milestones to do that. 
In the meantime, we recommend you to use our Docker image, that should work properly.

**Comment by kimal999** [comment]
Hi,
Thank you for your prompt response.  I'll check and let you know if there is any issue.
